"use client";

import React, { useState } from 'react';
import { Globe, Mic, MicOff, Bell, Download, CheckCircle2, Zap } from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';
import { motion, AnimatePresence } from 'framer-motion';
import { saveDownload } from '@/lib/firestore';

const COUNTRIES = [
  { value: 'India',     flag: '🇮🇳', label: 'India' },
  { value: 'USA',       flag: '🇺🇸', label: 'USA' },
  { value: 'UK',        flag: '🇬🇧', label: 'UK' },
  { value: 'Australia', flag: '🇦🇺', label: 'Australia' },
  { value: 'Canada',    flag: '🇨🇦', label: 'Canada' },
  { value: 'France',    flag: '🇫🇷', label: 'France' },
  { value: 'Germany',   flag: '🇩🇪', label: 'Germany' },
  { value: 'Japan',     flag: '🇯🇵', label: 'Japan' },
  { value: 'Brazil',    flag: '🇧🇷', label: 'Brazil' },
  { value: 'South Africa', flag: '🇿🇦', label: 'South Africa' },
  { value: 'Pakistan',  flag: '🇵🇰', label: 'Pakistan' },
  { value: 'Bangladesh', flag: '🇧🇩', label: 'Bangladesh' },
  { value: 'Sri Lanka', flag: '🇱🇰', label: 'Sri Lanka' },
];

const LANGUAGES = [
  { value: 'English',    label: 'English' },
  { value: 'Hindi',      label: 'हिंदी' },
  { value: 'Tamil',      label: 'தமிழ்' },
  { value: 'Telugu',     label: 'తెలుగు' },
  { value: 'Bengali',    label: 'বাংলা' },
  { value: 'Kannada',    label: 'ಕನ್ನಡ' },
  { value: 'Marathi',    label: 'मराठी' },
  { value: 'Gujarati',   label: 'ગુજરાતી' },
  { value: 'Urdu',       label: 'اردو' },
  { value: 'French',     label: 'Français' },
  { value: 'Spanish',    label: 'Español' },
  { value: 'Arabic',     label: 'العربية' },
  { value: 'German',     label: 'Deutsch' },
  { value: 'Japanese',   label: '日本語' },
  { value: 'Portuguese', label: 'Português' },
  { value: 'Chinese',    label: '中文' },
];

export default function TopNav() {
  const { country, setCountry, language, setLanguage, isAudioEnabled, toggleAudio, reminders } = useAppStore();
  const [showToast, setShowToast] = useState(false);
  const [toastMessage, setToastMessage] = useState('');

  const triggerToast = (msg: string) => {
    setToastMessage(msg);
    setShowToast(true);
    setTimeout(() => setShowToast(false), 3000);
  };

  const handleDownload = () => {
    triggerToast(`✅ ${country} Election Guide downloaded!`);
    const content = `VoteWise AI — Election Guide for ${country}\n\n1. Check Eligibility\n2. Register to Vote\n3. Find Polling Station\n4. Cast Your Vote!\n\nGenerated by VoteWise AI — ${new Date().toLocaleDateString()}`;
    const blob = new Blob([content], { type: 'text/plain' });
    const sizeKb = (blob.size / 1024).toFixed(1) + ' KB';
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const fileName = `${country}_Election_Guide.txt`;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    // Track this download in Firestore and notify CloudView
    saveDownload(fileName, country, sizeKb)
      .then(() => {
        // Signal CloudView to refresh its list
        window.dispatchEvent(new Event('votewise-download'));
      })
      .catch(console.error);
  };

  const handleNotification = () => {
    if (reminders.length > 0) {
      triggerToast(`🔔 You have ${reminders.length} active reminder${reminders.length > 1 ? 's' : ''}`);
    } else {
      triggerToast('🔕 No reminders set. Visit Calendar to add some!');
    }
  };

  const selectedCountry = COUNTRIES.find(c => c.value === country);

  return (
    <>
      <AnimatePresence>
        {showToast && (
          <motion.div
            initial={{ opacity: 0, y: -60, x: '-50%' }}
            animate={{ opacity: 1, y: 16, x: '-50%' }}
            exit={{ opacity: 0, y: -60, x: '-50%' }}
            className="fixed top-0 left-1/2 z-[100] glass-card px-5 py-3 rounded-2xl shadow-xl flex items-center space-x-3 border border-primary/30"
          >
            <CheckCircle2 className="w-4 h-4 text-primary flex-shrink-0" />
            <span className="font-medium text-sm text-foreground">{toastMessage}</span>
          </motion.div>
        )}
      </AnimatePresence>

      <nav className="h-16 w-full flex items-center justify-between px-4 md:px-6 flex-shrink-0 z-50 border-b border-white/[0.04] bg-black/20 backdrop-blur-xl">
        {/* Logo & Mobile Menu */}
        <div className="flex items-center space-x-3">
          <button 
            className="md:hidden p-2 -ml-2 text-muted-foreground hover:text-foreground"
            onClick={() => useAppStore.getState().setIsMobileMenuOpen(true)}
          >
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
          </button>
          
          <div className="relative w-9 h-9 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center shadow-lg shadow-indigo-500/30">
            <Globe className="w-5 h-5 text-white" />
            <div className="absolute -top-0.5 -right-0.5 w-3 h-3 bg-emerald-400 rounded-full border-2 border-background animate-pulse" />
          </div>
          <div className="hidden sm:block">
            <span className="font-bold text-lg text-foreground tracking-tight leading-none">
              Vote<span className="gradient-text">Wise</span> AI
            </span>
            <div className="flex items-center space-x-1">
              <Zap className="w-2.5 h-2.5 text-emerald-400" />
              <span className="text-[10px] text-emerald-400 font-medium">Powered by Gemini</span>
            </div>
          </div>
        </div>

        {/* Controls */}
        <div className="flex items-center space-x-2">
          {/* Country Selector - Hidden on mobile */}
          <div className="relative hidden md:block">
            <select
              className="appearance-none bg-white/[0.04] border border-white/[0.08] hover:border-primary/40 rounded-xl pl-3 pr-8 py-2 text-sm font-medium focus:ring-2 focus:ring-primary/50 outline-none transition-all cursor-pointer text-foreground backdrop-blur-sm"
              value={country}
              onChange={(e) => setCountry(e.target.value)}
            >
              {COUNTRIES.map(c => (
                <option key={c.value} className="bg-[#060a12]" value={c.value}>
                  {c.flag}  {c.label}
                </option>
              ))}
            </select>
            <div className="pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground text-xs">▾</div>
          </div>

          {/* Language Selector - Hidden on mobile */}
          <div className="relative hidden md:block">
            <select
              className="appearance-none bg-white/[0.04] border border-white/[0.08] hover:border-primary/40 rounded-xl pl-3 pr-8 py-2 text-sm font-medium focus:ring-2 focus:ring-primary/50 outline-none transition-all cursor-pointer text-foreground backdrop-blur-sm"
              value={language}
              onChange={(e) => setLanguage(e.target.value)}
            >
              {LANGUAGES.map(l => (
                <option key={l.value} className="bg-[#060a12]" value={l.value}>
                  {l.label}
                </option>
              ))}
            </select>
            <div className="pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground text-xs">▾</div>
          </div>

          <div className="h-6 w-px bg-white/[0.08] mx-1 hidden md:block" />

          <button onClick={handleNotification}
            className="relative p-2.5 rounded-xl bg-white/[0.04] border border-white/[0.08] text-muted-foreground hover:text-foreground hover:border-primary/40 transition-all"
            title="Notifications"
          >
            <Bell className="w-4 h-4" />
            {reminders.length > 0 && (
               <span className="absolute top-1.5 right-1.5 w-2 h-2 bg-indigo-500 rounded-full animate-pulse" />
            )}
          </button>

          <button onClick={toggleAudio}
            className={`p-2.5 rounded-xl border transition-all ${
              isAudioEnabled
                ? 'bg-primary/20 text-primary border-primary/40 shadow-lg shadow-primary/20'
                : 'bg-white/[0.04] border-white/[0.08] text-muted-foreground hover:text-foreground hover:border-primary/40'
            }`}
            title={isAudioEnabled ? 'Voice responses ON' : 'Voice responses OFF'}
          >
            {isAudioEnabled ? <Mic className="w-4 h-4" /> : <MicOff className="w-4 h-4" />}
          </button>

          <button onClick={handleDownload}
            className="hidden md:flex btn-primary-glow items-center space-x-2 px-4 py-2 rounded-xl font-semibold text-sm text-white"
          >
            <Download className="w-4 h-4" />
            <span>Download PDF</span>
          </button>
        </div>
      </nav>
    </>
  );
}
